version: '3.7'
services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
  db:
    image: mongo
    ports:
      - "27017:27017"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - api
      - web

